#!/usr/bin/env bash
# dispatch_task.sh — task dispatcher for cord blood SLURM array jobs.
#
# Usage:
#   dispatch_task.sh <method> <embedding> <seed> <outdir> <data_path>
#
# Maps a (method, embedding, seed, outdir) tuple to the correct underlying
# training (or eval-only) invocation. Honours per-method flags:
#   - PRESCIENT, TIGON: --well_col split --test_values test
#   - OT-CFM, SF2M:     --no_standardize (cord blood embeddings are pre-scaled)
#   - MIOFlow+GAE:      raw obsm (X_pca, DM_EigenVectors) for GAE to re-standardize
#     [Tier 2 — included for completeness; tier-2 SLURM job picks this up.]
#
# Every method writes to $OUTDIR. The launcher pipes stdout+stderr to a
# per-task log file, so SLURM failures don't pollute other tasks' logs.
set -euo pipefail

if [[ $# -ne 5 ]]; then
    echo "usage: $0 <method> <embedding_obsm_key> <seed> <outdir> <data_path>" >&2
    exit 2
fi

METHOD="$1"
EMBEDDING="$2"           # X_pca_scaled or DM_EigenVectors_scaled
SEED="$3"
OUTDIR="$4"
DATA="$5"

# Resolve n_dims from the embedding name
case "$EMBEDDING" in
    X_pca_scaled|X_pca_harmony_scaled) NDIMS=30 ;;
    DM_EigenVectors_scaled)
        # Read uns['dm_n_dims'] from the adata; fail loud if unreadable
        NDIMS=$(/rds/user/wz369/hpc-work/LIBS/mamba/envs/PINN_env/bin/python -c "
import scanpy as sc
a = sc.read_h5ad('$DATA', backed='r')
print(int(a.uns['dm_n_dims']))
" 2>/dev/null) || { echo "ERROR: failed to read uns['dm_n_dims'] from $DATA" >&2; exit 2; }
        [[ -n "$NDIMS" ]] || { echo "ERROR: empty NDIMS from $DATA" >&2; exit 2; }
        ;;
    *) echo "Unknown embedding: $EMBEDDING" >&2; exit 2 ;;
esac

PYTHON_PINN=/rds/user/wz369/hpc-work/LIBS/mamba/envs/PINN_env/bin/python
PYTHON_MIOFLOW=/rds/user/wz369/hpc-work/LIBS/mamba/envs/mioflow/bin/python
PYTHON_FLOW="singularity exec --nv /rds/user/wz369/hpc-work/containers/flow.sif python"
PYTHON_SCDIFFEQ_DIR=/rds/user/wz369/hpc-work/scDiffEq
PROJ=/rds/user/wz369/hpc-work/PINN_dynamics

# Cord-blood training durations — restored to full-pilot values (Klein defaults
# where applicable). The SLURM task runs eval AFTER training; the `--save N`
# / `every_n_epochs=N` controls how many intermediate checkpoints get produced.
# For a periodic mid-training eval sweep, see `scripts/cordblood/eval_sweep.sh`
# (post-training sweep over all saved checkpoints — pdp + PRESCIENT only;
# otcfm/sf2m/mioflow/tigon/trajectorynet save only the final ckpt).
PDP_MAX_EPOCHS=${PDP_MAX_EPOCHS:-400}        # pdp Lightning default
PDP_SAVE_EVERY=${PDP_SAVE_EVERY:-100}        # save a checkpoint every 100 epochs
PRESCIENT_PRETRAIN_EPOCHS=${PRESCIENT_PRETRAIN_EPOCHS:-500}
PRESCIENT_TRAIN_EPOCHS=${PRESCIENT_TRAIN_EPOCHS:-2500}
PRESCIENT_SAVE_EVERY=${PRESCIENT_SAVE_EVERY:-100}
OTCFM_NITERS=${OTCFM_NITERS:-100000}         # Klein default
SF2M_NITERS=${SF2M_NITERS:-100000}
MIOFLOW_EPOCHS=${MIOFLOW_EPOCHS:-100}
TIGON_NITERS=${TIGON_NITERS:-10000}
TRAJECTORYNET_NITERS=${TRAJECTORYNET_NITERS:-10000}

# Per-method env mapping (see docs/cordblood/environment.md):
#   pdp                 → PINN_env (user override; CFM trainer in pseudodynamics_plus)
#   prescient/otcfm/sf2m/deepruot → flow.sif singularity
#   mioflow/tigon/trajectorynet   → mioflow mamba env
#   scdiffeq            → uv at scDiffEq project
case "$METHOD" in
    pdp)                         PY="$PYTHON_PINN" ;;
    prescient|otcfm|sf2m|deepruot) PY="$PYTHON_FLOW" ;;
    mioflow|tigon|trajectorynet) PY="$PYTHON_MIOFLOW" ;;
    scdiffeq)                    PY="uv run --directory $PYTHON_SCDIFFEQ_DIR python" ;;
    *) echo "Unknown method: $METHOD" >&2; exit 2 ;;
esac

# NDIMS reader uses PINN_env regardless of method (just a scanpy import)
cd "$PROJ"

mkdir -p "$OUTDIR"

echo "==> $METHOD  emb=$EMBEDDING  seed=$SEED  ndims=$NDIMS  outdir=$OUTDIR"

case "$METHOD" in

    pdp)
        # PdP config is at <outdir>/V0_config.json (generated by _generate_configs.py).
        # The CFM-aware trainer lives in the pseudodynamics_plus repo.
        # pseudodynamics_plus/data is a symlink → PINN_dynamics/data, so the
        # trainer can read data/cordblood_addpop.h5ad without staging.
        CFG="$OUTDIR/V0_config.json"
        if [[ ! -f "$CFG" ]]; then
            echo "PDP config missing: $CFG (run _generate_configs.py)"
            exit 2
        fi
        PDP_PLUS=/rds/user/wz369/hpc-work/pseudodynamics_plus
        ( cd "$PDP_PLUS" && $PY main_train.py --config "$CFG" -G 0 --seed "$SEED" --max_epochs "$PDP_MAX_EPOCHS" )
        # Locate the trained config (pdp_plus saves it under the log_name dir post-training)
        LOG_NAME=$(/usr/bin/jq -r .raw_args.log_name "$CFG")
        if [[ -z "$LOG_NAME" || "$LOG_NAME" == "null" ]]; then
            echo "ERROR: could not extract raw_args.log_name from $CFG" >&2
            exit 2
        fi
        # pdp_plus saves the trained config as V<version>_config.json where version
        # is set from SLURM_JOB_ID. Pick the most-recent V*_config.json.
        TRAIN_CFG=$(ls -t "$PDP_PLUS/logs/$LOG_NAME/pde_params_tsense"/V*_config.json 2>/dev/null | head -1)
        if [[ -z "$TRAIN_CFG" || ! -f "$TRAIN_CFG" ]]; then
            echo "ERROR: pdp trained V*_config.json not found under $PDP_PLUS/logs/$LOG_NAME/pde_params_tsense/" >&2
            exit 2
        fi
        echo "  pdp eval using config: $TRAIN_CFG"
        $PYTHON_PINN scripts/pseudodynamics+/03_evaluate.py \
            --config_path "$TRAIN_CFG" \
            --data_path "$DATA" \
            --F_obs_path data/CordBlood/F_obs_day17.csv \
            --clone_proportions data/CordBlood/clone_proportions_day17.csv \
            --celltype_col def_lab \
            --n_sims_fate 100 --n_sims_w2 10 \
            --output_dir "$OUTDIR/eval"
        ;;

    prescient)
        # Prep — use HUMAN gene sets (uppercased from mouse_geneset/) so
        # PRESCIENT's growth-weight auto-compute matches cord blood's human gene
        # symbols. See data/human_geneset/README.md for the conversion provenance.
        $PY scripts/prescient/01_prepare_data.py \
            --data_path "$DATA" \
            --output_dir "$(dirname "$OUTDIR")" --run_name "$(basename "$OUTDIR")" \
            --obsm_key "$EMBEDDING" --n_dims "$NDIMS" \
            --tp_col timepoint_tx_days \
            --well_col split --test_values test \
            --celltype_col def_lab \
            --growth_mode auto \
            --birth_gst data/human_geneset/human_GOBP_cellcycle.csv \
            --death_gst data/human_geneset/human_hallmark_apoptosis.csv
        # Train — train_epochs=100 by default (env-overridable)
        $PY scripts/prescient/02_train.py \
            --data_path "$OUTDIR/data.pt" \
            --out_dir   "$OUTDIR/train" \
            --config    pca \
            --pretrain_epochs "$PRESCIENT_PRETRAIN_EPOCHS" \
            --train_epochs    "$PRESCIENT_TRAIN_EPOCHS" \
            --save            "$PRESCIENT_SAVE_EVERY" \
            --seed "$SEED" --gpu 0
        # Eval on best checkpoint
        # PRESCIENT eval initializes CUBLAS on first forward pass; when 3 seeds
        # run concurrently (same SLURM task) this causes CUBLAS_STATUS_NOT_INITIALIZED.
        # Fix: serialise all PRESCIENT evals in the same job via a job-scoped flock
        # on a tmp lock file. Train and prep still run in parallel.
        MODEL_DIR=$(find "$OUTDIR/train" -name "train.best.pt" -exec dirname {} \; | head -1)
        if [[ -n "$MODEL_DIR" ]]; then
            PRESCIENT_LOCK="${TMPDIR:-/tmp}/prescient_eval_${SLURM_JOB_ID:-$$}.lock"
            (
                flock -x 200
                $PY scripts/prescient/03_evaluate.py \
                    --model_dir "$MODEL_DIR" \
                    --data_path "$DATA" \
                    --obsm_key "$EMBEDDING" --n_dims "$NDIMS" \
                    --tp_col timepoint_tx_days --celltype_col def_lab \
                    --F_obs_path data/CordBlood/F_obs_day17.csv \
                    --clone_proportions data/CordBlood/clone_proportions_day17.csv \
                    --output_dir "$OUTDIR/eval"
            ) 200>"$PRESCIENT_LOCK"
        else
            echo "WARN: prescient train.best.pt not found under $OUTDIR/train; skipping eval" >&2
        fi
        ;;

    otcfm)
        $PY scripts/otcfm/02_train.py \
            --data_path "$DATA" \
            --obsm_key "$EMBEDDING" --n_dims "$NDIMS" \
            --tp_col timepoint_tx_days \
            --save_dir "$OUTDIR" \
            --niters "$OTCFM_NITERS" --batch_size 256 --sigma 0.1 --lr 1e-4 \
            --seed "$SEED" --gpu 0 \
            --no_standardize
        # obsm_key/n_dims/tp_col are read from model_dir/config.json by the eval
        # script; passing them on the CLI causes "unrecognized arguments" error.
        $PY scripts/otcfm/03_evaluate.py \
            --model_dir "$OUTDIR" \
            --data_path "$DATA" \
            --celltype_col def_lab \
            --F_obs_path data/CordBlood/F_obs_day17.csv \
            --clone_proportions data/CordBlood/clone_proportions_day17.csv
        ;;

    sf2m)
        $PY scripts/sf2m/02_train.py \
            --data_path "$DATA" \
            --obsm_key "$EMBEDDING" --n_dims "$NDIMS" \
            --tp_col timepoint_tx_days \
            --save_dir "$OUTDIR" \
            --niters "$SF2M_NITERS" --batch_size 256 --sigma 0.05 --lr 1e-4 \
            --seed "$SEED" --gpu 0 \
            --no_standardize
        # obsm_key/n_dims/tp_col are read from model_dir/config.json by the eval
        # script; passing them on the CLI causes "unrecognized arguments" error.
        $PY scripts/sf2m/03_evaluate.py \
            --model_dir "$OUTDIR" \
            --data_path "$DATA" \
            --celltype_col def_lab \
            --F_obs_path data/CordBlood/F_obs_day17.csv \
            --clone_proportions data/CordBlood/clone_proportions_day17.csv
        ;;

    deepruot)
        # External training; we only run eval against pre-trained models.
        EXT_MODEL_DIR="/rds/user/wz369/hpc-work/DeepRUOTv2/results/cordblood_${EMBEDDING}_s${SEED}"
        if [[ ! -d "$EXT_MODEL_DIR" ]]; then
            echo "DeepRUOT model dir not found: $EXT_MODEL_DIR — skip (train externally first)" >&2
            exit 3
        fi
        $PY scripts/DeepRUOT/03_evaluate.py \
            --model_dir "$EXT_MODEL_DIR" \
            --data_path "$DATA" \
            --obsm_key "$EMBEDDING" --n_dims "$NDIMS" \
            --device cpu \
            --tp_col timepoint_tx_days --celltype_col def_lab \
            --F_obs_path data/CordBlood/F_obs_day17.csv \
            --clone_proportions data/CordBlood/clone_proportions_day17.csv \
            --output_dir "$OUTDIR"
        ;;

    scdiffeq)
        $PY scripts/scdiffeq/klein_fate_eval_scdiffeq.py \
            --data_path "$DATA" \
            --obsm_key "$EMBEDDING" --n_dims "$NDIMS" \
            --tp_col timepoint_tx_days --celltype_col def_lab \
            --F_obs_path data/CordBlood/F_obs_day17.csv \
            --clone_proportions data/CordBlood/clone_proportions_day17.csv \
            --output_dir "$OUTDIR" \
            --seed "$SEED"
        ;;

    mioflow)
        # MIOFlow+GAE re-standardizes internally — pass RAW obsm key (strip _scaled)
        RAW_EMBEDDING="${EMBEDDING%_scaled}"
        # `01_train_with_gae.py` writes to <output_dir>/<exp_name>/, so set
        # output_dir = parent of OUTDIR + exp_name = basename(OUTDIR) so the
        # final dir is OUTDIR itself.
        $PY scripts/MIOFlow/01_train_with_gae.py \
            --data_path "$DATA" \
            --obsm_key "$RAW_EMBEDDING" --n_dims "$NDIMS" \
            --obs_time_key timepoint_tx_days \
            --output_dir "$(dirname "$OUTDIR")" \
            --exp_name "$(basename "$OUTDIR")" \
            --seed "$SEED"
        $PY scripts/MIOFlow/03_evaluate.py \
            --model_dir "$OUTDIR" \
            --data_path "$DATA" \
            --obsm_key "$RAW_EMBEDDING" --n_dims "$NDIMS" \
            --obs_time_key timepoint_tx_days --celltype_col def_lab \
            --F_obs_path data/CordBlood/F_obs_day17.csv \
            --clone_proportions data/CordBlood/clone_proportions_day17.csv
        ;;

    tigon)
        $PY scripts/TIGON/01_prepare_data.py \
            --data_path "$DATA" \
            --output_dir "$(dirname "$OUTDIR")" --run_name "$(basename "$OUTDIR")" \
            --obsm_key "$EMBEDDING" --n_dims "$NDIMS" \
            --tp_col timepoint_tx_days \
            --well_col split --test_values test \
            --celltype_col def_lab \
            --dataset_name cordblood \
            --seed "$SEED"
        $PY scripts/TIGON/02_train.py \
            --input_dir "$OUTDIR" --save_dir "$OUTDIR" \
            --dataset cordblood --niters "$TIGON_NITERS" --seed "$SEED" --gpu 0
        $PY scripts/TIGON/03_evaluate.py \
            --data_dir "$OUTDIR" \
            --checkpoint "$OUTDIR/ckpt.pth" \
            --data_path "$DATA" \
            --celltype_col def_lab \
            --F_obs_path data/CordBlood/F_obs_day17.csv \
            --clone_proportions data/CordBlood/clone_proportions_day17.csv \
            --output_dir "$OUTDIR/eval"
        ;;

    trajectorynet)
        # 01_prepare_data uses --obsm_key/--n_dims and writes <name>.npz;
        # 02_train uses --embedding_name/--max_dim and --data_path pointing AT the npz.
        # 02_train doesn't accept --seed (seeded via numpy/torch elsewhere).
        $PY scripts/TrajectoryNet/01_prepare_data.py \
            --data_path "$DATA" \
            --output_dir "$(dirname "$OUTDIR")" --run_name "$(basename "$OUTDIR")" \
            --obsm_key "$EMBEDDING" --n_dims "$NDIMS" \
            --tp_col timepoint_tx_days \
            --well_col Well \
            --celltype_col def_lab \
            --dataset_name cordblood \
            --seed "$SEED"
        $PY scripts/TrajectoryNet/02_train.py \
            --data_path "$OUTDIR/cordblood.npz" \
            --embedding_name "$EMBEDDING" --max_dim "$NDIMS" \
            --save_dir "$OUTDIR" \
            --niters "$TRAJECTORYNET_NITERS" \
            --gpu 0
        $PY scripts/TrajectoryNet/03_evaluate.py \
            --data_dir "$OUTDIR" --model_dir "$OUTDIR" \
            --data_path "$DATA" --device cpu \
            --tp_col timepoint_tx_days --celltype_col def_lab \
            --F_obs_path data/CordBlood/F_obs_day17.csv \
            --clone_proportions data/CordBlood/clone_proportions_day17.csv
        ;;

    *)
        echo "Unknown method: $METHOD" >&2
        exit 2
        ;;
esac

echo "==> DONE  $METHOD  $EMBEDDING  s$SEED"
